### ISSUE TITLE
Support Bugs with Package

### ISSUE THREAD

**Issue by devinmatte** [devinmatte/wasp#32]
Allow the user to point towards a bugs section, like the spec: https://docs.npmjs.com/files/package.json#bugs

Add support for adding bugs when using the `-p` flag.

**Comment by ilimugur** [comment]
I'd like to work on this if it hasn't been taken by someone else, yet.

**Comment by devinmatte** [comment]
@ilimugur Looks available still. Go for it

**Comment by ilimugur** [comment]
I went for it, and created a pull request. Implemented something simple and straightforward, based on the documentation you provided in the description of the issue. Basically both url and email info are asked during the "wasp init -p" stage, and they default to empty string. Only the ones that are not an empty string are feature on package.json. (Also, if neither is entered, no bug information is added to package.json.

**Comment by ilimugur** [comment]
I went for it, and created the pull request #35
